project '../../VPNclient-engine-ios/cntrlr.xcodeproj'
platform :ios, '12.0'
use_frameworks!


target 'VPNclientEngineFlutter' do
  use_frameworks!
  #  pod 'VPNclientEngine', :git => 'https://github.com/VPNclient/VPNclient-engine-ios.git', :tag => '0.1.0'
  pod 'VPNclientEngine', :path => '../../VPNclient-engine-ios'
end

target 'TunnelExtension' do
  #  pod 'VPNclientTunnel', :git => 'https://github.com/VPNclient/VPNclient-engine-ios.git', :tag => '0.1.0'
 pod 'VPNclientTunnel', :path => '../../VPNclient-engine-ios'
end